<?php
return [
    ["-", "全局"],
    ["admin::index/index", "首页"],
    ["-", "用户"],
    ["admin::base@user@index/index", "后台用户列表"],
    ["admin::base@user@index/add", "添加后台用户显示"],
    ["admin::base@user@index/doadd", "添加后台用户处理"],
    ["admin::base@user@index/edit", "编辑后台用户显示"],
    ["admin::base@user@index/doedit", "编辑后台用户处理"],
    ["admin::base@user@index/editpwd", "修改后台用户密码显示"],
    ["admin::base@user@index/doeditpwd", "修改后台用户密码处理"],
    ["admin::base@user@index/lock", "锁定/解锁后台用户"],
    ["admin::base@user@index/setting", "个人设置显示页面"],
    ['admin::base@user@index/crop', '上传个人头像'],
    ['admin::base@user@index/modifiPwd', '修改个人密码'],
    ["-", "权限"],
    ["admin::base@access@access/view", "权限查看"],
    ["admin::base@access@role/index", "角色列表"],
    ['admin::base@access@role/add', '角色添加显示'],
    ['admin::base@access@role/doadd', '角色添加处理'],
    ['admin::base@access@role/edit', '角色编辑显示'],
    ['admin::base@access@role/doedit', '角色编辑处理'],
    ['admin::base@access@role/delete', '角色删除'],
    ['admin::base@access@role/accessMg', '角色权限管理显示'],
    ['admin::base@access@role/accessSave', '角色权限管理更新'],
    ['admin::base@access@reportr/index', '汇报关系管理显示'],
    ['admin::base@access@reportr/doEdit', '汇报关系调整'],
    ["-", "数据"],
    ['admin::base@data@map/index', '数据字典管理'],
    ['admin::base@data@map/add', '数据字典添加显示'],
    ['admin::base@data@map/doadd', '数据字典添加处理'],
    ['admin::base@data@map/addoption', '字典数据添加显示'],
    ['admin::base@data@map/doaddoption', '字典数据添加处理'],
    ['admin::base@data@map/del', '字典删除'],
    ['admin::base@data@map/updateoption', '字典数据更新'],
    ['admin::base@data@map/deloption', '字典数据删除'],
    ['admin::base@data@map/edit', '数据字典编辑显示'],
    ['admin::base@data@map/doedit', '数据字典编辑处理'],
    ["admin::base@data@attachment/index", "文件管理"],
    ['admin::base@data@attachment/addgroup', '添加文件组显示'],
    ['admin::base@data@attachment/doaddgroup', '添加文件组处理'],
    ['admin::base@data@attachment/deletegroup', '文件组删除'],
    ['admin::base@data@attachment/deletefile', '删除文件'],
    ['admin::base@data@attachment/showbind', '查看文件绑定'],
    ["admin::base@data@syslog/index", "系统日志"],
    ["admin::base@data@backup/index", "数据库备份"],
    ['admin::base@data@backup/backup', '数据库备份处理'],
    ['admin::base@data@backup/restore', '数据库还原'],
    ['admin::base@data@backup/doRestore', '数据库还原处理'],
    ['admin::base@data@backup/upyun', '数据库上传到云'],
    ['admin::base@data@cache/clear', '缓存管理'],
    ['admin::base@data@cache/doClear', 'redis缓存清空处理'],
    ['admin::base@data@cache/doCompileClear', '模板引擎清空处理'],
    ['admin::base@data@cache/doFileClear', '文件缓存清空处理'],

];



